---
- name: Download & install talosctl
  ansible.builtin.get_url:
    url: "https://github.com/talos-systems/talos/releases/latest/download/talosctl-{{ ansible_facts['system'] | lower }}-{{ architecture | lower }}"
    dest: /usr/local/bin/talosctl
    mode: '0755'
  become: true
